version: "3.9"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "80:80" # Expose frontend on standard HTTP port
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:3000/api # Replace with your API domain or IP
    restart: always

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000" # Backend will listen on port 3000 internally
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=database
    restart: always

  db:
    container_name: db
    image: "postgres:13"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

volumes:
  db-data:
