# Use the official Node.js image as the base image
FROM node:20.5.1

# Set the working directory
WORKDIR /app

# Copy package.json and yarn.lock (or package-lock.json for npm)
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Expose the port for the development server
EXPOSE 3000

# Start the development server
CMD ["npm","run", "start:dev"]
